In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
pd = pd.read_csv('merged_data.csv')

,0,2,3,100,101,102,103,104,105,106,...,110,111,112,113,114,115,116,117,118,119
0,0.208461,True,0,0.791539,1.000000,1.000000,1.00000,1.00000,1.000000,1.0000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000
1,0.481681,True,0,0.309858,1.000000,1.000000,1.00000,1.00000,1.000000,1.0000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000
2,0.420538,True,1,0.309858,0.579462,1.000000,1.00000,1.00000,1.000000,1.0000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000
3,0.859182,True,2,0.309858,0.579462,0.140818,1.00000,1.00000,1.000000,1.0000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000
4,0.171162,True,0,0.138697,0.579462,0.140818,1.00000,1.00000,1.000000,1.0000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0.315423,False,-1,0.003609,0.034373,0.002928,0.00008,0.00027,0.013412,0.0038,...,0.023717,0.016353,0.05163,0.003678,0.002267,0.001295,0.024526,0.07133,0.001911,0.060713
999996,0.230940,False,-1,0.003609,0.034373,0.002928,0.00008,0.00027,0.013412,0.0038,...,0.023717,0.016353,0.05163,0.003678,0.002267,0.001295,0.024526,0.07133,0.001911,0.060713
999997,0.933347,False,-1,0.003609,0.034373,0.002928,0.00008,0.00027,0.013412,0.0038,...,0.023717,0.016353,0.05163,0.003678,0.002267,0.001295,0.024526,0.07133,0.001911,0.060713
999998,0.971583,False,-1,0.003609,0.034373,0.002928,0.00008,0.00027,0.013412,0.0038,...,0.023717,0.016353,0.05163,0.003678,0.002267,0.001295,0.024526,0.07133,0.001911,0.060713
999999,0.988404,False,-1,0.003609,0.034373,0.002928,0.00008,0.00027,0.013412,0.0038,...,0.023717,0.016353,0.05163,0.003678,0.002267,0.001295,0.024526,0.07133,0.001911,0.060713

In [5]:
import numpy as np
from sklearn.model_selection import train_test_split

In [6]:
df = pd
train, test = train_test_split(df, train_size=0.90)

In [8]:
y_train = train['3']
# y_train

93955     -1
51905     -1
450071    -1
127824    15
580051    -1
          ..
906622     8
573394    -1
349626    19
926513    -1
350957    -1
Name: 3, Length: 900000, dtype: int64

In [9]:
x_train = train.drop(['3'], axis='columns')
# x_train

,0,2,100,101,102,103,104,105,106,107,...,110,111,112,113,114,115,116,117,118,119
93955,0.892796,False,0.050874,0.000105,0.016487,0.002138,0.007556,0.004969,0.008435,0.008835,...,0.071813,0.008934,0.010414,0.007572,0.072841,0.014894,0.005429,0.055821,0.025068,0.038078
51905,0.166012,False,0.041942,0.022456,0.001311,0.077438,0.000903,0.054956,0.013596,0.002791,...,0.001831,0.001270,0.129992,0.000503,0.042556,0.005475,0.135620,0.029233,0.022806,0.002026
450071,0.479751,False,0.000229,0.009704,0.001535,0.012904,0.018372,0.027380,0.025671,0.029745,...,0.002936,0.022214,0.008800,0.000181,0.000648,0.010619,0.003727,0.029854,0.008857,0.001860
127824,0.990591,True,0.048650,0.074849,0.041403,0.075967,0.010367,0.048212,0.241224,0.127473,...,0.031781,0.462895,0.462921,0.499995,0.465957,0.009409,1.000000,1.000000,1.000000,1.000000
580051,0.425522,False,0.134034,0.002813,0.007942,0.091591,0.021004,0.081057,0.007063,0.123265,...,0.056593,0.036713,0.076681,0.042588,0.040017,0.021164,0.092801,0.003072,0.015012,0.004375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
906622,0.018250,True,0.071106,0.039229,0.037940,0.169218,0.008038,0.069682,0.015570,0.003084,...,0.503827,0.393210,0.297824,0.038959,0.410854,1.000000,1.000000,1.000000,1.000000,1.000000
573394,0.259324,False,0.001360,0.000678,0.011924,0.004276,0.001889,0.032065,0.007455,0.001538,...,0.013888,0.021908,0.015760,0.002258,0.001441,0.017929,0.000964,0.019687,0.021923,0.008965
349626,0.892139,True,0.086791,0.017931,0.059498,0.197086,0.018423,0.017064,0.038709,0.232550,...,0.343089,0.004455,0.423771,0.236736,0.047349,0.280812,0.373726,0.128436,0.305071,0.107861
926513,0.127916,False,0.005105,0.022825,0.030580,0.012185,0.031437,0.032713,0.012480,0.005009,...,0.014473,0.047478,0.015626,0.048011,0.005095,0.030583,0.020317,0.000885,0.120858,0.008488
350957,0.575367,False,0.009904,0.024122,0.003902,0.001596,0.000867,0.020903,0.026206,0.014025,...,0.061620,0.003959,0.006418,0.005415,0.017458,0.026880,0.023525,0.055545,0.004035,0.004541

In [10]:
y_test = test['3']
# y_test

129617    4
949697   -1
656882   -1
969747   -1
47557    -1
         ..
430522   -1
682353   -1
247524   -1
895634   -1
763314   -1
Name: 3, Length: 100000, dtype: int64

In [11]:
x_test = test.drop(['3'], axis='columns')
# x_test

,0,2,100,101,102,103,104,105,106,107,...,110,111,112,113,114,115,116,117,118,119
129617,0.173170,True,0.054966,0.014691,0.000654,0.003426,0.006427,0.020380,0.042809,0.047592,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
949697,0.425525,False,0.054513,0.051152,0.000649,0.002307,0.003870,0.050805,0.024461,0.034198,...,0.021918,0.013041,0.005264,0.002664,0.054588,0.064601,0.107856,0.058400,0.002758,0.033443
656882,0.911850,False,0.042684,0.016457,0.063305,0.044919,0.032462,0.046400,0.008183,0.048980,...,0.025971,0.040716,0.057090,0.011199,0.028746,0.005374,0.051298,0.069508,0.040931,0.173676
969747,0.923386,False,0.011881,0.001897,0.014199,0.000074,0.002633,0.000113,0.050596,0.010471,...,0.000725,0.001485,0.005602,0.003426,0.000434,0.009166,0.004334,0.039169,0.020043,0.051843
47557,0.956879,False,0.001597,0.014969,0.045741,0.011708,0.005575,0.002958,0.004505,0.009777,...,0.000124,0.005222,0.001022,0.003105,0.041509,0.070887,0.054086,0.032687,0.060403,0.033754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430522,0.926928,False,0.055323,0.059042,0.059986,0.005889,0.019498,0.011971,0.004926,0.051702,...,0.037856,0.002307,0.000948,0.003594,0.049637,0.017016,0.042739,0.040731,0.006392,0.010858
682353,0.180230,False,0.000821,0.032715,0.011620,0.007996,0.007074,0.005980,0.000107,0.020205,...,0.025951,0.004140,0.001849,0.036637,0.005944,0.022603,0.012436,0.009943,0.027469,0.004428
247524,0.634506,False,0.034888,0.006826,0.021309,0.000292,0.075182,0.001867,0.024631,0.024362,...,0.000468,0.019889,0.019418,0.032057,0.027372,0.021168,0.004037,0.013766,0.003261,0.005150
895634,0.494658,False,0.049455,0.018841,0.079597,0.435063,0.067805,0.025021,0.286117,0.035333,...,0.005790,0.430835,0.038962,0.022448,0.231676,0.022195,0.291757,0.056717,0.261619,0.085960
763314,0.641224,False,0.056833,0.002640,0.000300,0.000153,0.014516,0.002847,0.079552,0.013704,...,0.010852,0.004837,0.005661,0.097943,0.003153,0.009737,0.000675,0.006503,0.018753,0.004399

In [12]:
x_train = train.drop(['2'], axis='columns')
x_train.drop(columns='3')
# y_train

93955     -1
51905     -1
450071    -1
127824    15
580051    -1
          ..
906622     8
573394    -1
349626    19
926513    -1
350957    -1
Name: 3, Length: 900000, dtype: int64

In [13]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

In [15]:
model = RandomForestClassifier(n_jobs=-1, verbose=True, n_estimators=2000)

In [ ]:
%time model.fit(x_train.drop(columns='3'), y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:   45.4s
[Parallel(n_jobs=-1)]: Done 176 tasks      | elapsed:  4.0min
[Parallel(n_jobs=-1)]: Done 426 tasks      | elapsed:  9.6min

In [ ]:
x_test.drop(columns='2', inplace=True)

In [ ]:
%time model.score(x_test, y_test)