In [2]:
import pandas as pd
import sklearn.ensemble
import sklearn.model_selection

In [3]:
pd = pd.read_csv('merged_data.csv')  #reading our sythetic dataset
pd

,0,2,3,100,101,102,103,104,105,106,...,110,111,112,113,114,115,116,117,118,119
0,0.208461,True,0,0.791539,1.000000,1.000000,1.00000,1.00000,1.000000,1.0000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000
1,0.481681,True,0,0.309858,1.000000,1.000000,1.00000,1.00000,1.000000,1.0000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000
2,0.420538,True,1,0.309858,0.579462,1.000000,1.00000,1.00000,1.000000,1.0000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000
3,0.859182,True,2,0.309858,0.579462,0.140818,1.00000,1.00000,1.000000,1.0000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000
4,0.171162,True,0,0.138697,0.579462,0.140818,1.00000,1.00000,1.000000,1.0000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0.315423,False,-1,0.003609,0.034373,0.002928,0.00008,0.00027,0.013412,0.0038,...,0.023717,0.016353,0.05163,0.003678,0.002267,0.001295,0.024526,0.07133,0.001911,0.060713
999996,0.230940,False,-1,0.003609,0.034373,0.002928,0.00008,0.00027,0.013412,0.0038,...,0.023717,0.016353,0.05163,0.003678,0.002267,0.001295,0.024526,0.07133,0.001911,0.060713
999997,0.933347,False,-1,0.003609,0.034373,0.002928,0.00008,0.00027,0.013412,0.0038,...,0.023717,0.016353,0.05163,0.003678,0.002267,0.001295,0.024526,0.07133,0.001911,0.060713
999998,0.971583,False,-1,0.003609,0.034373,0.002928,0.00008,0.00027,0.013412,0.0038,...,0.023717,0.016353,0.05163,0.003678,0.002267,0.001295,0.024526,0.07133,0.001911,0.060713
999999,0.988404,False,-1,0.003609,0.034373,0.002928,0.00008,0.00027,0.013412,0.0038,...,0.023717,0.016353,0.05163,0.003678,0.002267,0.001295,0.024526,0.07133,0.001911,0.060713

In [4]:
import numpy as np
from sklearn.model_selection import train_test_split  #importing train_test_split in order to split dataset into train and test

In [5]:
df = pd
train, test = train_test_split(df, train_size=0.90)  #size of train dataset will be 90% of total size

In [6]:
train.head  #printing the head

<bound method NDFrame.head of                0      2   3       100       101       102       103       104  \
947344  0.244466  False  -1  0.032204  0.000925  0.019065  0.000288  0.013454
140076  0.833859  False  -1  0.019262  0.005180  0.019175  0.004787  0.018808
317514  0.448479  False  -1  0.003118  0.013790  0.015399  0.062645  0.069793
392952  0.336010  False  -1  0.049529  0.005822  0.001862  0.008615  0.005813
154345  0.076849   True  11  0.003059  0.008320  0.002788  0.074200  0.003963
...          ...    ...  ..       ...       ...       ...       ...       ...
349070  0.009608   True   9  0.030114  0.036360  0.005781  0.006825  0.043334
355619  0.946420   True  10  0.014748  0.039862  0.000364  0.106979  0.173930
777733  0.775259  False  -1  0.001701  0.000485  0.001240  0.004184  0.001744
474633  0.981366   True  16  0.056169  0.281547  0.285845  0.011143  0.012900
787015  0.078023   True   1  0.066529  0.057797  0.359675  0.002785  0.465811

             105       106  ...       110       111       112       113  \
947344  0.028993  0.039066  ...  0.016632  0.003992  0.018024  0.002798
140076  0.021236  0.048902  ...  0.006241  0.003484  0.005710  0.061524
317514  0.001050  0.092868  ...  0.037168  0.099018  0.080841  0.004020
392952  0.000706  0.047700  ...  0.026883  0.002734  0.022216  0.010242
154345  0.066548  0.008188  ...  0.000071  0.005558  0.006470  0.006696
...          ...       ...  ...       ...       ...       ...       ...
349070  0.038904  0.056952  ...  0.023169  0.004406  0.055740  0.180343
355619  0.021028  0.098692  ...  0.053580  1.000000  1.000000  1.000000
777733  0.000554  0.012235  ...  0.031414  0.026731  0.010296  0.008952
474633  0.007690  0.051354  ...  0.252146  0.062784  0.257244  0.011358
787015  0.235309  0.285204  ...  0.253893  1.000000  1.000000  1.000000

             114       115       116       117       118       119
947344  0.008980  0.007364  0.001642  0.062181  0.003741  0.006483
140076  0.069329  0.003926  0.006257  0.043001  0.017313  0.038655
317514  0.009271  0.019638  0.069743  0.076642  0.047832  0.002285
392952  0.016208  0.000459  0.003748  0.035545  0.047118  0.004778
154345  0.004362  0.008105  0.006134  0.015421  0.053800  0.003586
...          ...       ...       ...       ...       ...       ...
349070  0.158319  0.003079  0.186207  0.007203  0.064919  0.044904
355619  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
777733  0.022484  0.011910  0.017465  0.012490  0.010230  0.017160
474633  0.019045  0.276350  0.018634  1.000000  1.000000  1.000000
787015  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000

[900000 rows x 23 columns]>

In [7]:
y_train = train['3']   #the target variable
y_train

947344    -1
140076    -1
317514    -1
392952    -1
154345    11
          ..
349070     9
355619    10
777733    -1
474633    16
787015     1
Name: 3, Length: 900000, dtype: int64

In [8]:
x_train = train.drop(['3'], axis='columns')   #predictors

x_train

,0,2,100,101,102,103,104,105,106,107,...,110,111,112,113,114,115,116,117,118,119
947344,0.244466,False,0.032204,0.000925,0.019065,0.000288,0.013454,0.028993,0.039066,0.028783,...,0.016632,0.003992,0.018024,0.002798,0.008980,0.007364,0.001642,0.062181,0.003741,0.006483
140076,0.833859,False,0.019262,0.005180,0.019175,0.004787,0.018808,0.021236,0.048902,0.037876,...,0.006241,0.003484,0.005710,0.061524,0.069329,0.003926,0.006257,0.043001,0.017313,0.038655
317514,0.448479,False,0.003118,0.013790,0.015399,0.062645,0.069793,0.001050,0.092868,0.002444,...,0.037168,0.099018,0.080841,0.004020,0.009271,0.019638,0.069743,0.076642,0.047832,0.002285
392952,0.336010,False,0.049529,0.005822,0.001862,0.008615,0.005813,0.000706,0.047700,0.018083,...,0.026883,0.002734,0.022216,0.010242,0.016208,0.000459,0.003748,0.035545,0.047118,0.004778
154345,0.076849,True,0.003059,0.008320,0.002788,0.074200,0.003963,0.066548,0.008188,0.059958,...,0.000071,0.005558,0.006470,0.006696,0.004362,0.008105,0.006134,0.015421,0.053800,0.003586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349070,0.009608,True,0.030114,0.036360,0.005781,0.006825,0.043334,0.038904,0.056952,0.008102,...,0.023169,0.004406,0.055740,0.180343,0.158319,0.003079,0.186207,0.007203,0.064919,0.044904
355619,0.946420,True,0.014748,0.039862,0.000364,0.106979,0.173930,0.021028,0.098692,0.059364,...,0.053580,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
777733,0.775259,False,0.001701,0.000485,0.001240,0.004184,0.001744,0.000554,0.012235,0.001802,...,0.031414,0.026731,0.010296,0.008952,0.022484,0.011910,0.017465,0.012490,0.010230,0.017160
474633,0.981366,True,0.056169,0.281547,0.285845,0.011143,0.012900,0.007690,0.051354,0.007398,...,0.252146,0.062784,0.257244,0.011358,0.019045,0.276350,0.018634,1.000000,1.000000,1.000000
787015,0.078023,True,0.066529,0.057797,0.359675,0.002785,0.465811,0.235309,0.285204,0.176266,...,0.253893,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
y_test = test['3']
y_test

162895    -1
101412     6
197627    12
797288    -1
430619    12
          ..
645830    15
285221    10
117730    -1
934115    -1
714102    -1
Name: 3, Length: 100000, dtype: int64

In [10]:
x_test = test.drop(['3'], axis='columns')
x_test

,0,2,100,101,102,103,104,105,106,107,...,110,111,112,113,114,115,116,117,118,119
162895,0.212801,False,0.015537,0.009782,0.003275,0.061874,0.068252,0.022643,0.029420,0.011296,...,0.000090,0.099050,0.113940,0.057278,0.048421,0.007198,0.070308,0.006733,0.096156,0.003364
101412,0.774205,True,0.074308,0.014393,0.184338,0.044287,0.129345,0.383527,0.225795,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
197627,0.410710,True,0.040854,0.013930,0.186609,0.011124,0.111265,0.067501,0.368397,0.118454,...,0.051440,0.065399,0.011985,0.402331,0.020234,0.320711,1.000000,1.000000,1.000000,1.000000
797288,0.177089,False,0.045662,0.042086,0.077641,0.003279,0.043645,0.007895,0.008971,0.077450,...,0.094221,0.031448,0.001865,0.125679,0.039980,0.011227,0.000267,0.000604,0.098080,0.068282
430619,0.779133,True,0.020292,0.099355,0.041256,0.051770,0.339099,0.251820,0.082901,0.032876,...,0.456351,0.461482,0.220867,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
645830,0.322392,True,0.002357,0.027401,0.172915,0.008479,0.045282,0.398006,0.004356,0.014316,...,0.134863,0.028347,0.057312,0.411956,0.011409,0.004512,0.539919,0.393096,1.000000,1.000000
285221,0.138307,True,0.000414,0.060657,0.039868,0.033100,0.117673,0.012510,0.009066,0.041573,...,0.108012,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
117730,0.423027,False,0.015890,0.019501,0.031629,0.016849,0.002142,0.036778,0.079463,0.019095,...,0.000156,0.009605,0.004152,0.028956,0.001518,0.003004,0.003090,0.006139,0.004975,0.029063
934115,0.523106,False,0.004971,0.001269,0.039217,0.004255,0.040196,0.003969,0.041201,0.071573,...,0.004739,0.009017,0.001169,0.005372,0.028906,0.079825,0.000481,0.033766,0.075318,0.029263
714102,0.990968,False,0.002577,0.000621,0.000668,0.014199,0.031602,0.004652,0.035933,0.010953,...,0.004432,0.001346,0.054957,0.012160,0.004181,0.001313,0.007363,0.012120,0.042391,0.004452

In [11]:
x_train = train.drop(['2'], axis='columns')
x_train.drop(columns='3')


x_test.drop(columns='2', inplace=True)

In [12]:
import optuna    #importing optuna
from xgboost import XGBClassifier   #XGBoost classifier model

In [ ]:
def objective(trial):   
    
#changing parameters at every trial
    param = {
                "n_estimators" : trial.suggest_int('n_estimators', 0, 1000),  #suggest_int is for the range of of the parameter
                'max_depth':trial.suggest_int('max_depth', 2, 25),
                'reg_alpha':trial.suggest_int('reg_alpha', 0, 5),
                'reg_lambda':trial.suggest_int('reg_lambda', 0, 5),
                'min_child_weight':trial.suggest_int('min_child_weight', 0, 5),
                'gamma':trial.suggest_int('gamma', 0, 5),
                'learning_rate':trial.suggest_loguniform('learning_rate',0.005,0.5),
                'colsample_bytree':trial.suggest_discrete_uniform('colsample_bytree',0.1,1,0.01),
                'nthread' : -1,
                'verbosity' : 3,
                'njobs' : -1,
                'tree_method': 'gpu_hist'
            }
    model = XGBClassifier(**param)  #picking model as XGBoost classifier

    model.fit(x_train.drop(columns='3'), y_train)   #fitting the model

    return model.score(x_test, y_test)

study = optuna.create_study(direction='maximize')  
study.optimize(objective, n_trials=100)

trial = study.best_trial

print('Accuracy: {}'.format(trial.value))
print("Best hyperparameters: {}".format(trial.params))

[I 2021-04-06 16:27:05,421] A new study created in memory with name: no-name-1e8c159c-c821-4034-ab5d-2ed36e087eaa
c:\users\hpj12\appdata\local\programs\python\python38\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[16:27:05] DEBUG: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_gpu_hist.cu:892: [GPU Hist]: Configure
[16:27:05] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:541:
Parameters: { njobs } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[16:27:06] ======== Monitor: SketchContainer ========
[16:27:06] MakeCuts: 0.000832s, 1 calls @ 832us

[16:27:06] Prune: 0.000521s, 1 calls @ 521us

[16:27:06] ScanInput: 0.001438s, 1 calls @ 1438us

[16:27:06] Unique: 0.000349s, 1 calls @ 349us

[16:27:09] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.